# README

The purpose of this project is to
`[briefly describe the project's goals and objectives]`

## Reproducing the analysis

Run the following code from the project working directory:

```r
if (!requireNamespace("projr", quietly = TRUE)) {
  if (!requireNamespace("remotes", quietly = TRUE)) {
    install.packages("remotes")
  }
  remotes::install_github("SATVILab/projr")
}
projr::projr_build_dev()
```

<!--
Change the above instructions, e.g. specify non-default parameters or
another approach entirely.
-->

## Directory Structure

This project follows a structured directory layout to organise input
materials, generated outputs, and temporary files efficiently:

- `_reference/`: Static documents that are not generated by analyses,
  such as assignment questions and reference materials.
  - `docs`
    - Reference documentation, separated by year.
    - `2026`
      - Contains the following key documents:
        - Course outline
        - Q&A prompt instructions
- `_content/`: Content intended for Amathuba. Generated here (taken from `docs/`) or elsewhere.
  - `general`
    - Documents that do not fit in another category.
  - `notes`
    - Regression notes, covering all sections.
  - `w1`:
    - Week one material.
    - `prerequisites`:
      - Statistical theory and linear algebra prerequisites for regression.
      - Files:
        - `DemRegW0LinearAlgebra.html`:
          - Demonstrates linear algebra concewpts with `R` code.
        - `NotesRegW1S0Prereq.html`:
          - Statistical theory and linear algebra prerequisites notes. 
        - `SlidesRegW0S1PrereqLA.pdf`:
          - Slides which `VideoW1S0LA.mp4` speaks through. Came before the `NotesRegW1S0Prereq.html` notes, but were used for the video, and so are retained to make the video easier to follow along to.
          - It has several inaccuracies that are corrected in the corresponding `Notes` file:
            - Slides: Orthogonal matrix columns do not necessarily have unit length. Notes (correct): Orthogonal matrix columns do have unit length.
            - Slides: Covariance matrices are positive definite. Notes (correct): Covariance matrices are positive semidefinite, and may be positive definite if the random variables are linearly independent.
    - `slides`:
      - `SlidesRegW1S1Intro.pdf`:
        - Slides for the first lecture of week one. Rehashes course outline and motivates regression section.
      - `SlidesRegW1S3IntroMVN.pdf`:
        - Slides for the third lecture of week one. Introduces multivariate normal distribution.
- `_raw_data/`: Raw, unprocessed data files.
- `docs/`: Rendered documents produced from R Markdown (`Rmd`) or
  Quarto (`qmd`) scripts.
- `_output/`: Final analysis results, processed data, and exported
  reports.
- `_tmp/`: Temporary storage for cached outputs, intermediate
  results, and shared files.
- `w0-w6/`: Source code for generating the content in `docs/`, organized by week.

### Detailed Directory Structure

#### `_reference/`



## Links

- `[URLs to data sources (e.g. OneDrive), GitHub repos, etc.]`

## Details

`[Methods, timeline, team, data sources, software/tools, etc.]`

## Change Log

Summary of updates is included below.
For more detailed run information, including scripts run and configurations used, see [BUILDLOG.md](BUILDLOG.md).

```{r, echo=FALSE, results='asis'}
if (file.exists("CHANGELOG.md")) {
  cat(readLines("CHANGELOG.md", warn = FALSE), sep = "
")
} else {
  cat("No CHANGELOG.md found.")
}
```

